-- Configure vim options and keymaps
vim.g.mapleader = ";"
require("config.options")

ActiveThemes = require("config.active-themes")

-- Set up lazy.nvim

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

-- Load plugins and themes
require("lazy").setup({
    spec = {
        { import = "plugins" },
        { import = "themes" },

        { import = "lsp" },
    }
})

vim.cmd.colorscheme(ActiveThemes.vimTheme)

-- Set up keymaps last to allow plugins to override
require("config.keymaps")

-- Note: lazy-lock.json

-- This file is automatically generated by lazy.nvim to lock plugin versions.
-- Do not edit this file manually. Instead, use `:Lazy update` to update plugins
-- and regenerate this file.
